### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by saifulbabo67646** [sha-el/sha-el-design#102]
I am just trying to add this package on next js project 
this is my code sample. Below share my error code
`import '../styles/globals.css'
import type { AppProps } from 'next/app'
import { ThemeProvider } from 'sha-el-design/lib/components/Theme/Theme';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <ThemeProvider theme="LIGHT">
      <Component {...pageProps} />
    </ThemeProvider>
  )
}
export default MyApp`

And the error is 

[https://raw.githubusercontent.com/saifulbabo67646/Facebook-Video-Downloader/master/error%20for%20sha-el-design.png](https://raw.githubusercontent.com/saifulbabo67646/Facebook-Video-Downloader/master/error%20for%20sha-el-design.png)
And The Error code in console is 
`C:\Users\Saiful islam\nextjs\sha-el-design\my-app\node_modules\sha-el-design\lib\components\Theme\Theme.js:1
import * as React from 'react';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.sha-el-design/lib/components/Theme/Theme (C:\Users\Saiful islam\nextjs\sha-el-design\my-app\.next\server\pages\_app.js:83:18)
    at __webpack_require__ (C:\Users\Saiful islam\nextjs\sha-el-design\my-app\.next\server\webpack-runtime.js:25:42)
    at Object../pages/_app.tsx (C:\Users\Saiful islam\nextjs\sha-el-design\my-app\.next\server\pages\_app.js:19:98)`
 
Is There have a solution please?

**Comment by anitnilay20** [comment]
@saifulbabo67646 Hey did you find a solution for this?

**Comment by anitnilay20** [comment]
Closing due to inactivity.
